### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by zjpiazza** [okta/samples-js-react#105]
I just cloned the samples-js-react repo, npm installed the dependencies and tried to start up a development server. When I load the page I see the menu at the top but no contents on the rest of the screen. If I click the "Login" link at the top, I'm redirected to a blank page. Opening the Chrome console shows the following exception getting triggered:

`Access to XMLHttpRequest at 'https://<mysubdomain>.okta.com/oauth2/default/.well-known/openid-configuration' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

I'm not very experienced with React so I'm unsure if this is something in my local configuration causing this behavior or if the package is broken somehow. I'm using dotenv file to pass the issuer and client ID. Any help would be greatly appreciated!

**Comment by zjpiazza** [comment]
Clearly I didn't RTFM, sorry!

https://developer.okta.com/docs/guides/enable-cors/overview/

**Comment by axelkouassi** [comment]
In a scenario of a server-side Back-End producing services through APIs and  ReactJS Front-End consuming those services. When getting that CORS at the front end despite that the front end "http://loccalhost:3000" has been added as a Trusted Origin as well as the back-end "http://localhost:5000", who is responsible for handling that CORS, the back-end or the front-end?
![image](https://user-images.githubusercontent.com/18536146/149035756-2770c38e-4944-4873-b47f-2b38cbdaef91.png)
