### ISSUE TITLE
Registration failed with Sign-in widget

### ISSUE THREAD

**Issue by ey52fpv** [okta/samples-js-react#109]
Registration failing with custom attribute. Otherwise it results in success with base attributes.

{errorCode: "E0000001", errorSummary: "Api validation failed: null", errorLink: "E0000001",…}
errorCauses: [{errorSummary: "Registration cannot be completed at this time", reason: "UNKNOWN",…}]
0: {errorSummary: "Registration cannot be completed at this time", reason: "UNKNOWN",…}
domain: "registration request"
errorSummary: "Registration cannot be completed at this time"
reason: "UNKNOWN"
errorCode: "E0000001"
errorId: "oaeXsTbBwLdRTa423R_1JcklQ"
errorLink: "E0000001"
errorSummary: "Api validation failed: null"

**Comment by swiftone** [comment]
@ey52fpv - You may be encountering issues specific to your org setup.  I suggest reaching out to our support team at developers@okta.com - they can get details about your use case and suggest solutions.

**Comment by swiftone** [comment]
Closing as stale (any case with our support team is independent and is not impacted by closing this issue).
