### ISSUE TITLE
AuthSdkError

### ISSUE THREAD

**Issue by aarontanzk** [okta/samples-js-react#114]
Hi when npm start and accessed using machine name instead of localhost, AuthSdkError shows up as the app is not using HTTPS.

How to resolve this issue?

Thanks !

**Comment by mraible** [comment]
You are correct. We have special consideration for localhost. You might be able to use mkcert to create a certificate for your machine name.

https://github.com/FiloSottile/mkcert

**Comment by swiftone** [comment]
@aarontanzk - As mentioned above, "localhost" is allowed to connect without using https, but any machine name is not.  If you cannot use localhost, we recommend using a certificate and running over HTTPS.

**Comment by aarontanzk** [comment]
Q1: there was a proposed workaround using cookies.secure ? How would this work ?

Q2: is this error specific to the react sdk? Are there other ways around the machine name serving over http?

**Comment by aarontanzk** [comment]
Also, i'm using a Django backend server, would this be able to serve React over HTTPS?

**Comment by swiftone** [comment]
@aarontanzk - 

> workaround using cookies.secure ? How would this work ?

Where you pass additional options to the `<Security>` component, you can pass 
```
        <Security issuer='https://{yourOktaDomain}.com/oauth2/default'
                  clientId='{clientId}'
                  redirectUri={window.location.origin + '/implicit/callback'} 
                  cookies={ { secure: false } }
        >
```

This is found (in the admittedly too difficult path, we will fix that) by seeing this where the `<Security>` config ( https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#configuration-options ) points you to https://github.com/okta/okta-auth-js#configuration-reference

Note, however, that this means the cookies will not be set with the Secure flag, meaning that they can be used on an HTTP connection.  We strongly recommend against using HTTP in production.

> is this error specific to the react sdk? Are there other ways around the machine name serving over http?

The error is unrelated to React, or even to our SDKs.  PKCE requires secure webcrypto, and browsers don't allow the use of secure webcrypto on HTTP.  There is a built-in exception for localhost in the browser itself. 

> i'm using a Django backend server, would this be able to serve React over HTTPS?

I can't answer anything specific about using or configuring Django - that'd be a question for that community.  I'd expect serving HTTPS (including with React) is something such an established product would be able to do, though I don't know how involved the configuration would be.

**Comment by swiftone** [comment]
Closing this issue as stale - if there is a code problem/request, feel free to reopen this issue or open a new issue with additional details.
