### ISSUE TITLE
Introspect API

### ISSUE THREAD

**Issue by avatar296** [okta/samples-js-react#115]
We're using this demo with the introspect api on the /oauth2/v1/introspect using the generated pkce token.  Is this possible?  Would it be possible to get an example using the rest api?

**Comment by swiftone** [comment]
@avatar296 - Can you clarify what you mean by "the rest api?"

**Comment by avatar296** [comment]
We ended up figuring it out.  I'm referring to https://developer.okta.com/docs/reference/api/oidc/#introspect.  When using the introspection endpoint the auth server needed to be included. i.e. /oauth2/v1/introspect should be /oauth2/default/v1/introspect
