### ISSUE TITLE
Problem - Verify link from Sign Up returns back Error

### ISSUE THREAD

**Issue by sourceful-sharon** [okta/samples-js-react#116]
- Enable Okta Self-Sign up
- User gets an email with a verify link
- Link redirects to /implicit/callback
- Page renders an error: "AuthSdkError: OAuth flow response state doesn't match request state"
- Clicking on the Login button does the redirect correctly and correctly logs the user in

Why does this happen?

**Comment by swiftone** [comment]
@sourceful-sharon - thanks for the question.  I've seen some related issues and we're chasing down how to update our documentation.

To summarize what is happening, imagine a scenario without email:
- app sends user elsewhere (such as the okta site from your app site)
- "elsewhere" makes whatever check and redirects user back to the app site.

App site wants to make sure this new request is something it started, so:
- in the first step (where it redirected away) it sends a "state" parameter that contains something unpredictable. 
- When the other site redirects the user back to the app site, it will send it with the same state parameter it came with.  
- When the user loads the app and says "I'm legit", the app will check this state param to make sure it matches the state param it sent it out with.

This all works for web-based redirects, but for you the link in the email is not including the state param (which is what the error message is saying)  As this is outside of the code, I suggest reaching out to our support team at developers@okta.com and they can give you better direction (and help gather feedback on how we can improve our documentation).

hope that helps!

**Comment by aarongranick-okta** [comment]
@sourceful-sharon Were you able to find a resolution to this issue?
internal ref: OKTA-304955

**Comment by sourceful-sharon** [comment]
Sorry @aarongranick-okta I moved to auth0 which had a path that worked instead.
