### ISSUE TITLE
okta-hosted-login - Failed to Load Config...

### ISSUE THREAD

**Issue by slackgadget** [okta/samples-js-react#145]
I hit an issue running the okta-hosted-login. 
```
Starting the development server...

/Users/pc/Dev/octa/samples-js-react/okta-hosted-login/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: Failed to load config "airbnb" to extend from.
Referenced from: /Users/pc/Dev/octa/samples-js-react/.eslintrc.json
    at configMissingError (/Users/pc/Dev/octa/samples-js-react/okta-hosted-login/node_modules/@eslint/eslintrc/lib/config-array-factory.js:289:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/pc/Dev/octa/samples-js-react/okta-hosted-login/node_modules/@eslint/eslintrc/lib/config-array-factory.js:877:23)
    at ConfigArrayFactory._loadExtends (/Users/pc/Dev/octa/samples-js-react/okta-hosted-login/node_modules/@eslint/eslintrc/lib/config-array-factory.js:780:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/pc/Dev/octa/samples-js-react/okta-hosted-login/node_modules/@eslint/eslintrc/lib/config-array-factory.js:719:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/pc/Dev/octa/samples-js-react/okta-hosted-login/node_modules/@eslint/eslintrc/lib/config-array-factory.js:664:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/Users/pc/Dev/octa/samples-js-react/okta-hosted-login/node_modules/@eslint/eslintrc/lib/config-array-factory.js:510:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/pc/Dev/octa/samples-js-react/okta-hosted-login/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:378:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/pc/Dev/octa/samples-js-react/okta-hosted-login/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:397:20) {
  messageTemplate: 'extend-config-missing',
  messageData: {
    configName: 'airbnb',
    importerName: '/Users/pc/Dev/octa/samples-js-react/.eslintrc.json'
  }
```

The base eslint config needs to be in the same folder as package.json, node_modules, and where you run the eslint command.

found the suggestion here : [https://github.com/airbnb/javascript/issues/2202](https://github.com/airbnb/javascript/issues/2202)

Copying `.eslintrc.json` from `samples-js-react` to `samples-js-react/okta-hosted-login` got everything working for me. 
NB I did have some issues loading up the eslint libraries so it's possible this is related to that rather than the project code you have here.

**Comment by aarongranick-okta** [comment]
@slackgadget are you using `npm` or `yarn` as a package manager? Although `yarn` is standard for react development, theses samples were built using `npm`

**Comment by slackgadget** [comment]
yup using `npm` ...running on MacOS Mojave 10.14.6

**Comment by aarongranick-okta** [comment]
@slackgadget I don't understand why the eslint config would be loaded by the react-scripts "start" script. What command are you running that produces this error? Have you modified the sample in any way?

**Comment by Naught0** [comment]
@aarongranick-okta I'm receiving the same error. The first time I inadvertently used `yarn install`. I `rm -rf`'d and re-cloned to be safe and used npm this time. I'm receiving this error:
```Failed to load config "airbnb" to extend from```
And subsequently mentions `.eslintrc.json`

I did try copying the file as OP did, but to no avail.

npm: 7.0.8
node: 15.1.0

**Comment by phyolim** [comment]
did you do ```npm install``` in both the samples-js-react dir and okta-hosted-login dir? I think I saw the same thing when I didn't run npm install on the main directory. I'm using yarn.

**Comment by Naught0** [comment]
I just gave that a shot & it worked. I'm not sure if I missed it or if I'm a noob and this is typical, but the readme doesn't mention having to install in both dirs, does it? 

Anyway, cheers 🍻

**Comment by phyolim** [comment]
I think they expect you to start the server from main dir using script in main package.json like - 
```yarn okta-hosted-login-server```

**Comment by aarongranick-okta** [comment]
@slackgadget @Naught0 @phyolim When running `npm install` from the root directory (on a clean repository), it will also run `npm install` in each of the child folders: https://github.com/okta/samples-js-react/blob/master/package.json#L18

This repo was built and tested using `npm` and we have seen some strange issues when `npm` and `yarn` are mixed.

After the node modules are installed you can start the server from the top-level directory using `npm run okta-hosted-login-server` or you can `cd okta-hosted-login` and do `npm run start` https://github.com/okta/samples-js-react/blob/master/okta-hosted-login/package.json#L19

**Comment by slackgadget** [comment]
> @slackgadget @Naught0 @phyolim When running `npm install` from the root directory (on a clean repository), it will also run `npm install` in each of the child folders: https://github.com/okta/samples-js-react/blob/master/package.json#L18
> 
> This repo was built and tested using `npm` and we have seen some strange issues when `npm` and `yarn` are mixed.
> 
> After the node modules are installed you can start the server from the top-level directory using `npm run okta-hosted-login-server` or you can `cd okta-hosted-login` and do `npm run start` https://github.com/okta/samples-js-react/blob/master/okta-hosted-login/package.json#L19

Yup, pulled clean code,  and tested the above. That worked fine for me. Probably be good to add these steps to the readme as @Naught0 suggests. @aarongranick-okta want to close the issue?

**Comment by sdtacoma** [comment]
> 
> 
> > @slackgadget @Naught0 @phyolim When running `npm install` from the root directory (on a clean repository), it will also run `npm install` in each of the child folders: https://github.com/okta/samples-js-react/blob/master/package.json#L18
> > This repo was built and tested using `npm` and we have seen some strange issues when `npm` and `yarn` are mixed.
> > After the node modules are installed you can start the server from the top-level directory using `npm run okta-hosted-login-server` or you can `cd okta-hosted-login` and do `npm run start` https://github.com/okta/samples-js-react/blob/master/okta-hosted-login/package.json#L19
> 
> Yup, pulled clean code, and tested the above. That worked fine for me. Probably be good to add these steps to the readme as @Naught0 suggests. @aarongranick-okta want to close the issue?

Yes, it would be really nice to add this step to the readme as @Naught0 and @slackgadget suggested.
