### ISSUE TITLE
Authorization header Message.jsx line 32

### ISSUE THREAD

**Issue by slarge08** [okta/samples-js-react#155]
[This line](https://github.com/okta/samples-js-react/blob/master/okta-hosted-login/src/Messages.jsx#L30) I had to change it to `Authorization: Bearer ${accessToken.value}`  or accessToken.accessToken for this to work with the example node js resource server you provided. Otherwise, it just sends the whole access token object back to the node server and it doesn't know how to process

**Comment by oleksandrpravosudko-okta** [comment]
thanks for report @slarge08

adding a story for making token passing/reading consistent across sample apps
Internal Ref:
OKTA-349263

**Comment by shuowu-okta** [comment]
@slarge08 It is fixed in #156, close the issue.
