### ISSUE TITLE
yarn install reports vulnerabilities

### ISSUE THREAD

**Issue by DanielJoyce** [okta/samples-js-react#213]
33 vulnerabilities (14 moderate, 19 high)

**Comment by shuowu** [comment]
@DanielJoyce Thanks for reporting the issue! 

Internal Ref: OKTA-407488

**Comment by denysoblohin-okta** [comment]
`react-scripts` has 3 moderate vulns.
Detailed explanation in [here](https://github.com/facebook/create-react-app/issues/11174) and [here](https://overreacted.io/npm-audit-broken-by-design/)

Moved `react-scripts` to `devDependencies`
`npm audit --production` shows 0 vulns
