### ISSUE TITLE
SPA_CLIENT_ID reported as an error when CLIENT_ID is fine

### ISSUE THREAD

**Issue by anselmhookcodex** [okta/samples-js-react#271]
As far as I can tell vite.config.js has a test to see that SPA_CLIENT_ID is defined - however the application in reality looks for either CLIENT_ID or SPA_CLIENT_ID .  Therefore it is incorrect to test that SPA_CLIENT_ID is always defined.

**Comment by jaredperreault-okta** [comment]
@anselmhookcodex Thanks for the reporting, this should be fixed
