### ISSUE TITLE
Getting OAuthError: The '{0}' system claim could not be evaluated.

### ISSUE THREAD

**Issue by ssingwork** [okta/samples-js-react#33]
Don't see much in console also.  Any idea ?
Node : v9.2.0
Npm : 5.5.1
Windows 7

Navigated to http://localhost:8080/
16:14:33.927 VM49 bundle.js:87907 XHR finished loading: GET "http://localhost:8080/sockjs-node/info?t=1522365272507".
16:14:40.095 Navigated to http://localhost:8080/implicit/callback
16:14:42.371 abstract-xhr.js:132 XHR finished loading: GET "http://localhost:8080/sockjs-node/info?t=1522365281108".

**Comment by robertjd** [comment]
Is this an error that is being returned by our API?  It smells like an issue with authorization server configuration, such as a policy rule being invoked.  Are you working with a developer org on oktapreview (which has the "default" authorization server) or a different type of org?

**Comment by ssingwork** [comment]
Thanks! Yes, this something to do with our organization setup. I just create new user and working properly.
