### ISSUE TITLE
How to best integrate this to existing React app?

### ISSUE THREAD

**Issue by miriam-z** [okta/samples-js-react#35]
Best to move this sample-js-react into my existing React/Express app, or move existing React/Express app into this app? Because the code base is similar in each case...

**Comment by jmelberg-okta** [comment]
Hey @miriam-z!

Great question. I'd suggest taking a look at the [React Quickstart](https://developer.okta.com/quickstart/#/react/nodejs/express) on [developer.okta.com](https://developer.okta.com). The "quickstarts" were designed to show you how to plug into existing applications.

If you have any further questions, please reach out to us via the [Okta Developer Forums](devforum.okta.com)!
