### ISSUE TITLE
invalid_token - "The Token has expired" instead of redirect to Login.

### ISSUE THREAD

**Issue by thismax** [okta/samples-js-react#37]
Hi!  I'm using the okta-react SDK in my project, which is working well apart from the following issue:  upon access token expiry, the client does not redirect the user to the login page as expected and a blank view is rendered with the following error:

```
Uncaught (in promise)
  OAuthError
    errorCode: invalid_token
    errorSummary: "The Token has expired"
```

Upon refreshing the page, the client is redirected to the Login page, and the site functions normally.  This has made things pretty difficult to debug, since the issue goes away upon any change to the project, and I also haven't yet figured out how to change the access token age.  Looking for:

1. A resolution to access token expiry that redirects the client to the login page
2. A way of setting the max age of the access token.

It should be noted that simply destroying the token in local storage doesn't resolve the issue.

**Comment by aarongranick-okta** [comment]
Hi, @thismax thank you for taking the time to report this issue. I am sorry it has taken this long for us to reply. 

Normally an expired token should be automatically renewed by the `TokenManager`. This might not happen if `autoRenew` has been set to `false` or if there was a permanent error in renewing the token (It will happen if you have signed out of Okta in another tab). Your application can listen for events from the `TokenManager` and handle the `login_required` errorCode as shown here: https://github.com/okta/okta-auth-js#tokenmanageronevent-callback-context

Within a React component using the `withAuth` higher order component, the `TokenManager` would be available as `this.props.auth._oktaAuth.tokenManager`

Hopefully this information will help provide you with a decent solution. We are working to document this better and provide a cleaner default implementation for this case in an upcoming release.

Thank you for using Okta!
