### ISSUE TITLE
Login issue from another machine?

### ISSUE THREAD

**Issue by miriam-z** [okta/samples-js-react#38]
Using credentials saved in the OKTA portal, this sample-js-react, I was able to login successfully locally on my machine which I pushed into github repo and launched locally

cd custom-login
$ npm start

In browser localhost:8080 username and password, clicked LOGIN and works

but if my project was cloned on another machine, and upon launching using the same 

$ npm install at the root level as well as at the custom-login folder and then
cd custom-login
$npm start

 it reports
jquery.js:10245 OPTIONS https://%7Byouroktadomain%7D.com/api/v1/authn
net::ERR_NAME_NOT_RESOLVED

**Comment by bdemers** [comment]
How are you accessing the other machine? still `localhost:8080` or by other ip/hostname ?

**Comment by robertjd** [comment]
Hi @miriam-z , that error makes me think that the `.samples.config.js` file needs to be updated to include your org-specific information.  This file is explicitly excluded, via .gitignore, to prevent sensitive information from being committed to source control

**Comment by aarongranick-okta** [comment]
Configuration for your `ISSUER` and `CLIENT_ID` should be done on the local machine. These values are not checked into version control, and so must be setup after a git clone. This is described in the README: https://github.com/okta/samples-js-react
