### ISSUE TITLE
logout - missing

### ISSUE THREAD

**Issue by integral-llc** [okta/samples-js-react#39]
I'm following your sample on hot to integrate Okta into the React app from here https://developer.okta.com/quickstart/#/react/nodejs/express

it has the logout functionality that is missing from this github sample. Why?

looks to me like is not functional, after I call `this.props.auth.logout('/');` nothing happens, but if I refresh the page then I'm logged out. 

Can you complete this github sample to support the logout functionality?

Thx

**Comment by integral-llc** [comment]
for now I solved it this way
```
  logout = async () => {
    await this.props.auth.logout('/');
    window.location.reload();
  }

```
which seems to work, not sure if the right approach.

**Comment by aarongranick-okta** [comment]
@integral-llc We do recommend performing a `window.location.reload` after logout, so your approach is "right". 

But it is possible that the logout method may throw an exception if, for example, the current session is not valid. This can happen if the user has signed out in another browser tab. If `logout()` throws, the user may see an error or blank page and the reload will not occur. For additional resilience, we recommend to catch any errors before reload:

```
this.props.auth.logout()
.then(function() {
  console.log('successfully logged out');
})
.catch(function(err) {
  console.error(err);
})
.then(function() {
  // Reload app in unauthenticated state
  window.location.reload();
});
```
