### ISSUE TITLE
Social login

### ISSUE THREAD

**Issue by miguefl** [okta/samples-js-react#40]
I've tried to add Facebook/Google auth with these samples but I haven't been able to do it.

This is my Security component.

```

const config = {
  issuer: "url",
  redirect_uri: window.location.origin + "/implicit/callback",
  client_id: "client",
  idps: [
    { type: "FACEBOOK", id: "id" },
    { type: "GOOGLE", id: "id" }
  ],
  idpDisplay: "PRIMARY"
};

function Root() {
  return (
    <Switch>
      <Security
        issuer={config.issuer}
        client_id={config.client_id}
        redirect_uri={config.redirect_uri}
        idps={config.idps}
        idpDisplay={config.idpDisplay}
      >
        <Route exact path="/" component={Home} />
        <Route path="/implicit/callback" component={ImplicitCallback} />
        <Route path="/login" component={Login} />
      </Security>
    </Switch>
  );
}
```

Is there any way to configure social login with React okta library?

**Comment by jmelberg-okta** [comment]
Hey @miguefl,

The [`okta-react`](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react) library currently does not extend support for Social Login. We have [an open issue](https://github.com/okta/okta-oidc-js/issues/48) to add support for this in the near future, so I'd recommend following/watching that repo for updates.

Of course, you're more than welcome to use [`okta-auth-js`](https://github.com/okta/okta-auth-js) instead, the library `okta-react` uses under the hood.
