### ISSUE TITLE
More descriptive error message

### ISSUE THREAD

**Issue by haishengwu-okta** [okta/samples-js-react#42]
It's a bit frustration when I saw such page without any hints (no error from console and network as well)
wonder if we'd like to display error details which would be helpful for troubleshooting!
(given it's sample project, I doubt there would be security concern but please suggest)

![screen shot 2018-05-02 at 12 01 59 pm](https://user-images.githubusercontent.com/13139863/39543718-d9aaaa20-4e00-11e8-80f0-cf7cd0acaea0.png)

**Comment by robertjd** [comment]
Hey @haishengwu-okta , thanks for noticing this.  We're actually discussing how we want to handle these errors, see the conversation here: 

https://github.com/okta/okta-oidc-js/pull/236

Also: the error in your screenshot particularly confusing, which we're going to fix in the next version of Auth Js, you can see those changes here: https://github.com/okta/okta-auth-js/commit/02e6d06aebb45fa73629810b70c653773db9d95b#diff-398ed3b014436a5204583323ea29320b

**Comment by aarongranick-okta** [comment]
@haishengwu-okta It looks like the source of the error was that `responseMode` was somehow set to `query`, and the OIDC flow here requires `fragment`. We have logic for setting the default `responseMode` here: https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/lib/token.js#L593

I agree we can have a better description for this error. Thanks for reporting!
