### ISSUE TITLE
React -- log in with Google

### ISSUE THREAD

**Issue by kershnerd** [okta/samples-js-react#44]
Referencing this issue:
#https://github.com/okta/samples-js-react/issues/40

I have been going back and forth with Okta support on why logging in with google isn't working and base on the issue I referenced above, is it true this isn't implemented with React yet?  Okta support has been unable thus far to give me any answers yet.

So I cloned the custom-login demo and am able to authenticate with username and password to Okta.  I also set up the social provider so that when I click by custom button to login with google, it seems to work.  Google authenticates me and returns me to my `/implicit/callback` route.

Then I get the error:
`AuthSdkError: Unable to parse a token from the url`

But looking at the Okta logs, it looks like I was authenticated.  The token is correct but the `/implicit/callback` route doesn't parse the URL and save in local storage.

What's the deal?

Thanks!

**Comment by aarongranick-okta** [comment]
@kershnerd This issue is very old. I am hoping you were able to get this resolved? If you are still having issues with Okta we are here to help.

**Comment by kershnerd** [comment]
Resolved it by switching to Auth0.
