### ISSUE TITLE
Improve debuggability for okta-react

### ISSUE THREAD

**Issue by tsiq-swyx** [okta/samples-js-react#49]
currently when i have an auth error i get this:

![image](https://user-images.githubusercontent.com/35976578/40991220-072626d4-68c1-11e8-8d8e-35a55a04cc69.png)

and because everything is abstracted away inside `Security.js` and `ImplicitCallback.js`, i dont get to debug the error. thrown errors are caught. i suggest either log out more information about the errors, or just dont catch the thrown errors so we can debug things ourselves.

**Comment by tsiq-swyx** [comment]
my bug was caused by a leftover cookie from a session that i had left running overnight.

we pull the state from the cookie, but the cookie doesnt expire. so this is how the flow response state doesnt match request state.

![image](https://user-images.githubusercontent.com/35976578/41061848-042985fc-69a2-11e8-931a-85383acfb374.png)


so we may either want to 1) change the expiration strategy or 2) more strictly set the cookies.

**Comment by aarongranick-okta** [comment]
@tsiq-swyx The cookie is set before login redirect and should be cleared after login was successful. It is possible for a cookie to remain in place if the login was not successfully handled. 

Generally this is not a problem as long as you are using a unique route for your login redirect URI, such as `/implicit/callback` The route should only become activated during a login attempt, and it should redirect again immediately after processing the authorization tokens.

We have seen issues such as this if a shared route such as `/` is used for the callback. In this case there may be calls to `handleAuthentication` that do not have a matching login request. 

For debugging purposes, the source of the error is here: https://github.com/okta/okta-auth-js/blob/d4368a36f501a38aca13af10d193239608f2cf5c/packages/okta-auth-js/lib/token.js#L165

You may also want to use the [source map loader](https://github.com/webpack-contrib/source-map-loader) in your webpack config. This will load the source maps included with our libraries and should greatly help with debugging.
