### ISSUE TITLE
Might be useful to state that: CORS needs to be set up on Okta Console, for this code sample to work.

### ISSUE THREAD

**Issue by pompalini** [okta/samples-js-react#57]
Maybe it was just me, but I had to go to Console > API > Trusted Logins and then add:
![image](https://user-images.githubusercontent.com/7702056/47307017-d4601200-d625-11e8-812c-6ecf5b5c6adf.png)

Just a suggestion...

A part from this minor bump everything worked like a charm 🙌

**Comment by mraymond77** [comment]
Yes, would have been helpful. Please add to the readme.

**Comment by swiftone** [comment]
Hi @mraymond77 - 

Thanks for the feedback - the CORS setting in Trusted Origin should be automatically created (unless you already have a host of the same domain + port listed as trusted) when you create an SPA application in the Console.  

Can you recreate a situation where this is not the case?

**Comment by swiftone** [comment]
Closing due to lack of response.  If this is an issue for you, you can reopen this with more details or open a new issue and reference this one.
