### ISSUE TITLE
List Group Members throwing an error

### ISSUE THREAD

**Issue by Timothycocores** [okta/samples-js-react#60]
{
    "errorCode": "E0000007",
    "errorSummary": "Not found: Resource not found: {{GROUPID}} (UserGroup)",
    "errorLink": "E0000007",
    "errorId": "oaeIp2gJC9iR_mSLH6kapkAHw",
    "errorCauses": []
}

***NOTES***
Groupid removed as did not want this public

**Comment by swiftone** [comment]
List Group Members isn't part of the code samples - can you give more details about what you are trying to do and the code involved?
