### ISSUE TITLE
custom login sample app keeps loading even after successful login.

### ISSUE THREAD

**Issue by a-eid** [okta/samples-js-react#63]
I'm trying out the custom login app, after failing to implement it on my own, 
replacing the config file with my own config file and running the app, 

- on failed login it shows a failed to login message which is correct. 
- on successful login it just keeps on loading...

**Comment by swiftone** [comment]
Hi!  Thanks for your comment.  We're not able to replicate your bug - perhaps we aren't quite understanding what you mean by "keeps on loading".  Can you provide more detail?

**Comment by a-eid** [comment]
@swiftone Hi, so after I enter my correct credentials, the loading indicator does not go away it keeps on loading. if I enter wrong credentials it shows the error message.

**Comment by manueltanzi-okta** [comment]
Hi @a-eid!

Can you share your `.samples.config.js` configuration?

Thank you!

- Manuel

**Comment by a-eid** [comment]
@manueltanzi-okta I did follow a different example and it's working for me now, thanks.
