### ISSUE TITLE
Scope is not getting passed properly to okta-react

### ISSUE THREAD

**Issue by santhoshbalakrishnan** [okta/samples-js-react#64]
I tried adding 

```
<Security
         issuer={config.oidc.issuer}
         client_id={config.oidc.clientId}
         redirect_uri={config.oidc.redirectUri}
         scopes={config.oidc.scope}
> 
``` 

in App.jsx but even that is not getting reflected properly in the token.

**Comment by aarongranick-okta** [comment]
Is Security a child of the Router component?

**Comment by aarongranick-okta** [comment]
The properties passed to Security are passed through the "buildConfigObject" method: https://github.com/okta/okta-oidc-js/blob/master/packages/configuration-validation/src/lib.js#L31 @manueltanzi-okta

**Comment by swiftone** [comment]
Closing due to several updates to configuration-valdiation.  If you discover a related problem, please open a new issue.
