### ISSUE TITLE
Error in user guide on this JS SDK

### ISSUE THREAD

**Issue by kaienbcjdoapwkfldue** [okta/samples-js-react#73]
There is an error in the usage guide on this SDK here:

https://developer.okta.com/docs/guides/sign-into-spa/react/configure-the-sdk/

You need to pass an array to `scope` in the `config` like so:

```
const config = {
  clientId: '{clientId}',
  issuer: 'https://{yourOktaDomain}/oauth2/default',
  redirectUri: 'http://localhost:8080/implicit/callback',
  scope: ['openid', 'profile', 'email'],
};
```

With `'openid profile email'`, I don't get an automatic redirection to Okta when authentication is required. When manually triggering via `auth.login()`, I receive:

`Unhandled Rejection (TypeError): oauthParams.scopes.join is not a function`

**Comment by nbarbettini** [comment]
Good catch! Thanks 🙂 

@aarongranick-okta Can you check the code in the guide?

**Comment by swiftone** [comment]
Docs updated (a while, looks like we missed closing this issue at the time)
