### ISSUE TITLE
React custom-login

### ISSUE THREAD

**Issue by jakedurell** [okta/samples-js-react#75]
I am getting the following error displayed on the okta widget when I attempt to login:

**Unable to connect to the server. Please check your network connection.**

The console provides an additional error which I pasted below. 

I am unable to log in by using developer credentials. I am confident I set up the application and config file properly. I did not touch any other file.

> OPTIONS https://dev-######.okta.com.com/api/v1/authn net::ERR_CERT_COMMON_NAME_INVALID
  | send | @ | jquery.js:10245
-- | -- | -- | --
  | ajax | @ | jquery.js:9734
  | jqueryRequest | @ | jqueryRequest.js:17
  | httpRequest | @ | http.js:43
  | post | @ | http.js:118
  | postToTransaction | @ | tx.js:53
  | postToTransaction | @ | clientBuilder.js:173
  | ./node_modules/@okta/okta-signin-widget/node_modules/@okta/okta-auth-js/lib/clientBuilder.js.proto.signIn | @ | clientBuilder.js:176
  | doPrimaryAuth | @ | okta-sign-in.entry.js:40650
  | (anonymous) | @ | okta-sign-in.entry.js:40594
  | startTransaction | @ | okta-sign-in.entry.js:34007
  | save | @ | okta-sign-in.entry.js:40593
  | _fulfilled | @ | q.js:834
  | (anonymous) | @ | q.js:863
  | Promise.promise.promiseDispatch | @ | q.js:796
  | (anonymous) | @ | q.js:604
  | runSingle | @ | q.js:137
  | flush | @ | q.js:125
  | run | @ | setImmediate.js:40
  | runIfPresent | @ | setImmediate.js:69
  | onGlobalMessage | @ | setImmediate.js:109
  | postMessage (async) |   |  
  | registerImmediate | @ | setImmediate.js:120
  | setImmediate | @ | setImmediate.js:27
  | nextTick | @ | q.js:180
  | Promise.then | @ | q.js:856
  | (anonymous) | @ | okta-sign-in.entry.js:38702
  | triggerEvents | @ | backbone.js:352
  | triggerApi | @ | backbone.js:339
  | eventsApi | @ | backbone.js:137
  | Events.trigger | @ | backbone.js:329
  | __save | @ | okta-sign-in.entry.js:23553
  | (anonymous) | @ | underscore.js:804
  | submit | @ | okta-sign-in.entry.js:23037
  | dispatch | @ | jquery.js:5226
  | elemData.handle | @ | jquery.js:4878
-- | --

**Comment by swiftone** [comment]
@jakedurell  - Thanks for the report!

> https://dev-/######.okta.com.com/api/v1/authn

The ".com.com" here is almost certainly the problem.  Can you check your config to see if you have that, and remove the extra .com?

**Comment by jakedurell** [comment]
Yes, that was the issue. Thanks for giving it a closer look than I did :-/
