### ISSUE TITLE
Unhandled Rejection (OAuthError): The client specified not to prompt, but the user is not logged in.

### ISSUE THREAD

**Issue by preyansh98** [okta/samples-js-react#81]
Hi there! 

I'm constantly seeing this error that's only solved by emptying cache and hard reloading. 

**Steps to replicate:**
1. Login on the React app with Okta
2. Stay logged in and close browser
3. Open page again and error occurs

**Comment by swiftone** [comment]
This may be handled by https://github.com/okta/okta-auth-js/pull/247 when that is merged

**Comment by preyansh98** [comment]
Hi @swiftone, thanks for your response. 

I suppose the fix went in one of the releases, because the problem resolved itself by updating okta-react to the latest version.
