### ISSUE TITLE
Out-Of-Box Experience does not work

### ISSUE THREAD

**Issue by clearly** [okta/samples-js-react#98]
Identity Provider: Unknown
Error Code: server_error
Description: The requested feature is not enabled in this environment.

**Comment by swiftone** [comment]
@clearly - Thanks for the report.  Unfortunately, given only the information listed we can't diagnose the problem.  

Which of the two options (okta-hosted vs custom login) are you using?  What are you doing that triggers this output?  Did you create the config as described in the README?

**Comment by swiftone** [comment]
Closing due to lack of response.  If you (or anyone else reading) has problems, feel free to reopen or create a new issue with details.
